// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'push_notification_base.dart';

// **************************************************************************
// Generator: AnnotationBuilder
// **************************************************************************

///   This File is Generated by Dart Mem Annotation Generator
///   [AppPushNotificationBase] Annotated with [Mem] with [all] mode
///   Including:
///     Model Class, Entity Class and Mapper Class,
///     Model Classes includes [toJson] and [fromJson] functions, and Entity Classes are not!
///     Mappers will convert every filed in the class including [SubClasses], they should be annotated as well.
///     [Mem] Annotation will generate all these fields for all Classes, so all subclasses should decorated with annotation to generate model, entity and mapper to use them here
///     [Enums] also supported and they will be detected and count into account for mappers and also json conversion
///     Classes are decorated with [Freezed], other functions will generate with [Freezed]

///   Details:
///     Class: AppPushNotificationBase
///     Constructors Count: 1
///     Variables Count: 1

///   ==> Model Class:
@Freezed(toJson: true, fromJson: true)
class AppPushNotificationBaseModel with _$AppPushNotificationBaseModel {
  const factory AppPushNotificationBaseModel({
    final String? title,
  }) = _AppPushNotificationBaseModel;

  factory AppPushNotificationBaseModel.fromJson(Map<String, dynamic> json) =>
      _$AppPushNotificationBaseModelFromJson(json);
}

///   ==> Entity Class:
@Freezed(toJson: false, fromJson: false)
class AppPushNotificationBaseEntity with _$AppPushNotificationBaseEntity {
  const factory AppPushNotificationBaseEntity({
    final String? title,
  }) = _AppPushNotificationBaseEntity;
}

///   ==> Mapper Classes:
///   ==> Entity to Model Mapper Extension
extension MapperExtensionOnAppPushNotificationBaseEntity
    on AppPushNotificationBaseEntity {
  AppPushNotificationBaseModel get mapper => AppPushNotificationBaseModel(
        title: title,
      );
}

///   ==> Model to Entity Mapper Extension
extension MapperExtensionOnAppPushNotificationBaseModel
    on AppPushNotificationBaseModel {
  AppPushNotificationBaseEntity get mapper => AppPushNotificationBaseEntity(
        title: title,
      );
}
