// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'custom_duration.dart';

// **************************************************************************
// Generator: AnnotationBuilder
// **************************************************************************

///   This File is Generated by Dart Mem Annotation Generator
///   [CustomDuration] Annotated with [Mem] with [all] mode
///   Including:
///     Model Class, Entity Class and Mapper Class,
///     Model Classes includes [toJson] and [fromJson] functions, and Entity Classes are not!
///     Mappers will convert every filed in the class including [SubClasses], they should be annotated as well.
///     [Mem] Annotation will generate all these fields for all Classes, so all subclasses should decorated with annotation to generate model, entity and mapper to use them here
///     [Enums] also supported and they will be detected and count into account for mappers and also json conversion
///     Classes are decorated with [Freezed], other functions will generate with [Freezed]

///   Details:
///     Class: CustomDuration
///     Constructors Count: 1
///     Variables Count: 8

///   ==> Model Class:
@Freezed(toJson: true, fromJson: true)
class CustomDurationModel with _$CustomDurationModel {
  const factory CustomDurationModel({
    final int? year,
    final int? month,
    final int? week,
    final int? day,
    final int? hour,
    final int? minute,
    final int? second,
    final int? milliSecond,
  }) = _CustomDurationModel;

  factory CustomDurationModel.fromJson(Map<String, dynamic> json) =>
      _$CustomDurationModelFromJson(json);
}

///   ==> Entity Class:
@Freezed(toJson: false, fromJson: false)
class CustomDurationEntity with _$CustomDurationEntity {
  const factory CustomDurationEntity({
    final int? year,
    final int? month,
    final int? week,
    final int? day,
    final int? hour,
    final int? minute,
    final int? second,
    final int? milliSecond,
  }) = _CustomDurationEntity;
}

///   ==> Mapper Classes:
///   ==> Entity to Model Mapper Extension
extension MapperExtensionOnCustomDurationEntity on CustomDurationEntity {
  CustomDurationModel get mapper => CustomDurationModel(
        year: year,
        month: month,
        week: week,
        day: day,
        hour: hour,
        minute: minute,
        second: second,
        milliSecond: milliSecond,
      );
}

///   ==> Model to Entity Mapper Extension
extension MapperExtensionOnCustomDurationModel on CustomDurationModel {
  CustomDurationEntity get mapper => CustomDurationEntity(
        year: year,
        month: month,
        week: week,
        day: day,
        hour: hour,
        minute: minute,
        second: second,
        milliSecond: milliSecond,
      );
}
