// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'app_statistics_data.dart';

// **************************************************************************
// Generator: AnnotationBuilder
// **************************************************************************

///   This File is Generated by Dart Mem Annotation Generator
///   [AppStatisticsData] Annotated with [Mem] with [all] mode
///   Including:
///     Model Class, Entity Class and Mapper Class,
///     Model Classes includes [toJson] and [fromJson] functions, and Entity Classes are not!
///     Mappers will convert every filed in the class including [SubClasses], they should be annotated as well.
///     [Mem] Annotation will generate all these fields for all Classes, so all subclasses should decorated with annotation to generate model, entity and mapper to use them here
///     [Enums] also supported and they will be detected and count into account for mappers and also json conversion
///     Classes are decorated with [Freezed], other functions will generate with [Freezed]

///   Details:
///     Class: AppStatisticsData
///     Constructors Count: 1
///     Variables Count: 7

///   ==> Model Class:
@Freezed(toJson: true, fromJson: true)
class AppStatisticsDataModel with _$AppStatisticsDataModel {
  const factory AppStatisticsDataModel({
    final int? launches,
    final int? logins,
    final int? crashes,
    final int? pageOpens,
    final int? apiCalls,
    final DateTime? installDateTime,
    final Duration? installDuration,
  }) = _AppStatisticsDataModel;

  factory AppStatisticsDataModel.fromJson(Map<String, dynamic> json) =>
      _$AppStatisticsDataModelFromJson(json);
}

///   ==> Entity Class:
@Freezed(toJson: false, fromJson: false)
class AppStatisticsDataEntity with _$AppStatisticsDataEntity {
  const factory AppStatisticsDataEntity({
    final int? launches,
    final int? logins,
    final int? crashes,
    final int? pageOpens,
    final int? apiCalls,
    final DateTime? installDateTime,
    final Duration? installDuration,
  }) = _AppStatisticsDataEntity;
}

///   ==> Mapper Classes:
///   ==> Entity to Model Mapper Extension
extension MapperExtensionOnAppStatisticsDataEntity on AppStatisticsDataEntity {
  AppStatisticsDataModel get mapper => AppStatisticsDataModel(
        launches: launches,
        logins: logins,
        crashes: crashes,
        pageOpens: pageOpens,
        apiCalls: apiCalls,
        installDateTime: installDateTime,
        installDuration: installDuration,
      );
}

///   ==> Model to Entity Mapper Extension
extension MapperExtensionOnAppStatisticsDataModel on AppStatisticsDataModel {
  AppStatisticsDataEntity get mapper => AppStatisticsDataEntity(
        launches: launches,
        logins: logins,
        crashes: crashes,
        pageOpens: pageOpens,
        apiCalls: apiCalls,
        installDateTime: installDateTime,
        installDuration: installDuration,
      );
}
