// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'app_page_detail.dart';

// **************************************************************************
// Generator: AnnotationBuilder
// **************************************************************************

///   This File is Generated by Dart Mem Annotation Generator
///   [AppPageDetail] Annotated with [Mem] with [all] mode
///   Including:
///     Model Class, Entity Class and Mapper Class,
///     Model Classes includes [toJson] and [fromJson] functions, and Entity Classes are not!
///     Mappers will convert every filed in the class including [SubClasses], they should be annotated as well.
///     [Mem] Annotation will generate all these fields for all Classes, so all subclasses should decorated with annotation to generate model, entity and mapper to use them here
///     [Enums] also supported and they will be detected and count into account for mappers and also json conversion
///     Classes are decorated with [Freezed], other functions will generate with [Freezed]

///   Details:
///     Class: AppPageDetail
///     Constructors Count: 1
///     Variables Count: 5

///   ==> Model Class:
@Freezed(toJson: true, fromJson: true)
class AppPageDetailModel with _$AppPageDetailModel {
  const factory AppPageDetailModel({
    final String? pageRoute,
    final String? pageName,
    final int? bottomBarItemNumber,
    final bool? drawerPresence,
    final int? iconCode,
  }) = _AppPageDetailModel;

  factory AppPageDetailModel.fromJson(Map<String, dynamic> json) =>
      _$AppPageDetailModelFromJson(json);
}

///   ==> Entity Class:
@Freezed(toJson: false, fromJson: false)
class AppPageDetailEntity with _$AppPageDetailEntity {
  const factory AppPageDetailEntity({
    final String? pageRoute,
    final String? pageName,
    final int? bottomBarItemNumber,
    final bool? drawerPresence,
    final int? iconCode,
  }) = _AppPageDetailEntity;
}

///   ==> Mapper Classes:
///   ==> Entity to Model Mapper Extension
extension MapperExtensionOnAppPageDetailEntity on AppPageDetailEntity {
  AppPageDetailModel get mapper => AppPageDetailModel(
        pageRoute: pageRoute,
        pageName: pageName,
        bottomBarItemNumber: bottomBarItemNumber,
        drawerPresence: drawerPresence,
        iconCode: iconCode,
      );
}

///   ==> Model to Entity Mapper Extension
extension MapperExtensionOnAppPageDetailModel on AppPageDetailModel {
  AppPageDetailEntity get mapper => AppPageDetailEntity(
        pageRoute: pageRoute,
        pageName: pageName,
        bottomBarItemNumber: bottomBarItemNumber,
        drawerPresence: drawerPresence,
        iconCode: iconCode,
      );
}

///   This File is Generated by Dart Mem Annotation Generator
///   [AppPageDetailList] Annotated with [Mem] with [all] mode
///   Including:
///     Model Class, Entity Class and Mapper Class,
///     Model Classes includes [toJson] and [fromJson] functions, and Entity Classes are not!
///     Mappers will convert every filed in the class including [SubClasses], they should be annotated as well.
///     [Mem] Annotation will generate all these fields for all Classes, so all subclasses should decorated with annotation to generate model, entity and mapper to use them here
///     [Enums] also supported and they will be detected and count into account for mappers and also json conversion
///     Classes are decorated with [Freezed], other functions will generate with [Freezed]

///   Details:
///     Class: AppPageDetailList
///     Constructors Count: 1
///     Variables Count: 1

///   ==> Model Class:
@Freezed(toJson: true, fromJson: true)
class AppPageDetailListModel with _$AppPageDetailListModel {
  const factory AppPageDetailListModel({
    final List<AppPageDetailModel>? pageDetailListModel,
  }) = _AppPageDetailListModel;

  factory AppPageDetailListModel.fromJson(Map<String, dynamic> json) =>
      _$AppPageDetailListModelFromJson(json);
}

///   ==> Entity Class:
@Freezed(toJson: false, fromJson: false)
class AppPageDetailListEntity with _$AppPageDetailListEntity {
  const factory AppPageDetailListEntity({
    final List<AppPageDetailEntity>? pageDetailListEntity,
  }) = _AppPageDetailListEntity;
}

///   ==> Mapper Classes:
///   ==> Entity to Model Mapper Extension
extension MapperExtensionOnAppPageDetailListEntity on AppPageDetailListEntity {
  AppPageDetailListModel get mapper => AppPageDetailListModel(
        pageDetailListModel:
            pageDetailListEntity?.map((e) => e.mapper).toList(),
      );
}

///   ==> Model to Entity Mapper Extension
extension MapperExtensionOnAppPageDetailListModel on AppPageDetailListModel {
  AppPageDetailListEntity get mapper => AppPageDetailListEntity(
        pageDetailListEntity:
            pageDetailListModel?.map((e) => e.mapper).toList(),
      );
}
