// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'local_notification_base_model.dart';

// **************************************************************************
// Generator: AnnotationBuilder
// **************************************************************************

///   This File is Generated by Dart Mem Annotation Generator
///   [AppLocalNotificationBase] Annotated with [Mem] with [all] mode
///   Including:
///     Model Class, Entity Class and Mapper Class,
///     Model Classes includes [toJson] and [fromJson] functions, and Entity Classes are not!
///     Mappers will convert every filed in the class including [SubClasses], they should be annotated as well.
///     [Mem] Annotation will generate all these fields for all Classes, so all subclasses should decorated with annotation to generate model, entity and mapper to use them here
///     [Enums] also supported and they will be detected and count into account for mappers and also json conversion
///     Classes are decorated with [Freezed], other functions will generate with [Freezed]

///   Details:
///     Class: AppLocalNotificationBase
///     Constructors Count: 1
///     Variables Count: 1

///   ==> Model Class:
@Freezed(toJson: true, fromJson: true)
class AppLocalNotificationBaseModel with _$AppLocalNotificationBaseModel {
  const factory AppLocalNotificationBaseModel({
    final String? title,
  }) = _AppLocalNotificationBaseModel;

  factory AppLocalNotificationBaseModel.fromJson(Map<String, dynamic> json) =>
      _$AppLocalNotificationBaseModelFromJson(json);
}

///   ==> Entity Class:
@Freezed(toJson: false, fromJson: false)
class AppLocalNotificationBaseEntity with _$AppLocalNotificationBaseEntity {
  const factory AppLocalNotificationBaseEntity({
    final String? title,
  }) = _AppLocalNotificationBaseEntity;
}

///   ==> Mapper Classes:
///   ==> Entity to Model Mapper Extension
extension MapperExtensionOnAppLocalNotificationBaseEntity
    on AppLocalNotificationBaseEntity {
  AppLocalNotificationBaseModel get mapper => AppLocalNotificationBaseModel(
        title: title,
      );
}

///   ==> Model to Entity Mapper Extension
extension MapperExtensionOnAppLocalNotificationBaseModel
    on AppLocalNotificationBaseModel {
  AppLocalNotificationBaseEntity get mapper => AppLocalNotificationBaseEntity(
        title: title,
      );
}
